name: MurderMysteryLED
version: 0.0.1
api: [5.0.0]
author: LeyKey
main: mm\MurderMystery

commands:
  murdermystery:
    description: "Murder Mystery command"
    aliases: [mm, mrd]
    permission: "murdermystery.noop"
    
permissions:
  murdermystery.op:
    description: "Permission to all Setup Commands!"
    default: op
  murdermystery.noop:
    description: "Permission to all Non Op Commands!"
    default: true
  murdermystery.forcestart:
    description: "Force start a game"
    default: op
